apiVersion: v1
kind: Service
metadata:
  name: llamacpp-service
  namespace: llama-app
  labels:
    app: llamacpp
spec:
  type: NodePort
  ports:
  - port: 8084
    targetPort: 8084
    nodePort: 30083
    name: http
  - port: 9090
    targetPort: 9090
    # nodePort: auto-assigned
    name: metrics
  selector:
    app: llamacpp
